language: python
python:
- '3.6'
cache:
- pip
install:
- pip install -r requirements.txt
- pip install -e .
script:
- pytest
deploy:
  provider: pypi
  user: miniscruff
  password:
    secure: Oh+8A3KthR/L+oOUOWDBRYIQY6nseIPowXSyWNeEWpNZO22gHJ5NKIx5oN+jnLXO5mH2oWcZPlgbdHDZfXo3MeGHzZrxAMjSfBxB7GsTNf9/MGovY5X4ptgiSrQ/N4z0rANVw6cq4km4WMvncnHPO4uSNIu+0pzX49hDw1UjW+oPc4H1azM9bwfXcBKzIU0GnX11HpmIycdwmAmsh9s9AMZ+kJvflUNpsuw6LAHbG8kap0DGwNBCo8Wl20MjB0+D9QrEp3MygA118mdsCpwEVUFmG1OO7OaoKkjgJCpOuJS8EoSRJbh4T2ELolm5e6tlbVJvPgPDveSvj0ZwVDIxXic1j+FjsemQLnoWlGtMPCwTqFTDoSqXkL9fmmApETDdMy6s7OqPEwnmI85/u9kJ+tXFxnJY0GkmMvjOM9jRO7ZH/oSGOCK9zcjHI4A0Z/FI7bu1KHFgAGDjzRZXBFw6jw5p6ZMcfpDMJR7gdPEn9Ghx4LuZR+eY+PxbMZ0rtjRauORA6dJY43CQM58VZAn+ApkVymb4hNvCxqAOMUB3mFQwacstnNcwKdUvhYbnzMAFU6dRhX9I3yyoAdkn6WkY6SYioEsbjzJKoOAEbAS/Hkv7hw3oPjNi3pS8P95Dx+q4VzgLN1pEbv3l1cdLguGMZrokRix0w89lWw6oaOYFhc0=
  distributions: sdist bdist_wheel
