language: python
python:
- '3.6'
cache:
- pip
install:
- pip install -r requirements.txt
script:
- pytest
deploy:
  provider: pypi
  user: miniscruff
  password:
    secure: Gin4gdNurRgJ7FYoeeGmpfQO/GEMYj7T9R+wwxKAnxQpYs+BDksfRon+Fowb9fSSfIoAFfO13wwX/vnxjHhXywAzHLBgFwXQpAGDgPOjeXuuJF8hfG9c9/sUEjJ02i1BpbofKKVOCt74k4PYNfb4EejzzdfCVb+WfLWnjV1yVJwUQC8ijRFB2pO8gS5RUIBxP77qgTXCc1EPpSCMWcjJD6sh9/+9knjEdtJgh1WA3jBtA64elAi1f5A1bAPWWqy7zzJ4JMzvWEFS4zqUwr7Nn6vXODaE/rWF+8ljHMrz0AIsAgPNU2zvzrAGCc+ikaih1vFEXC251RDGjIdvuJe7Ozs0ojV+ePiLhNIljnP/xIjaO/nGrKd9TT5ApubFnOAMU1mRteypzV79G1IFS+RFBPhiCGoIn9JO34ZP8ERsXLPVG92OAdzHOeDuZrG4O5aj/xaZiWk6cnJkuRIL4F+XTyNk+stBr36pKGOzxcbnSfGcsQGbKGi18YFBhl7vULl3OicKmo2RJua+P8cK6l92FY08wCx2k4Yoj1l2VBycJxYaodVB8rsndkpDxmcYh0oMH/zYlcX6J/XHJAl3m14O4JC7lfFjhNj5LYKAlDvCDORCeWpCvNDetsB8+3XRgAwztgfVLT9PailvNGUgnnpIYeyBWXQf2eJt0VpZRWemaAU=
  distributions: sdist bdist_wheel
